In [1]:
import numpy as np
import pandas as pd


In [2]:
extra_df = pd.read_csv("actualextra.csv")
extra_df.head()

StudentID  Exam1  Exam2  Exam3
0          1   90.5    100     92
1          2   44.5     91     72
2          3   41.0     89     40
3          4   31.0     75     29
4          5   58.5     97     75

In [3]:
x = extra_df[["Exam1","Exam2","Exam3"]]
x

Exam1  Exam2  Exam3
0    90.5    100     92
1    44.5     91     72
2    41.0     89     40
3    31.0     75     29
4    58.5     97     75
5    77.5    100     89
6    85.0    100     99
7    51.0     90     44
8    60.5    100     69
9    62.0     81     40
10   77.0    100     72
11   51.5     96     74

In [4]:
from sklearn.preprocessing import StandardScaler
x_std = StandardScaler().fit_transform(x)

In [5]:
x_std

array([[ 1.67950689,  0.84471295,  1.17898576],
       [-0.92467233, -0.28157098,  0.26326867],
       [-1.1228164 , -0.5318563 , -1.20187869],
       [-1.68894232, -2.28385353, -1.70552309],
       [-0.13209605,  0.46928497,  0.40062623],
       [ 0.94354319,  0.84471295,  1.0416282 ],
       [ 1.36813763,  0.84471295,  1.49948674],
       [-0.55669048, -0.40671364, -1.01873527],
       [-0.01887086,  0.84471295,  0.1259111 ],
       [ 0.06604802, -1.53299758, -1.20187869],
       [ 0.9152369 ,  0.84471295,  0.26326867],
       [-0.52838419,  0.34414231,  0.35484037]])

In [6]:
import numpy as np
features = x_std.T
covariance_matrix = np.cov(features)
print(covariance_matrix)


[[1.09090909 0.7931588  0.86244769]
 [0.7931588  1.09090909 0.95439631]
 [0.86244769 0.95439631 1.09090909]]


In [7]:
eig_vals, eig_vecs = np.linalg.eig(covariance_matrix)
print('Eigenvectors \n%s' %eig_vecs)

Eigenvectors 
[[ 0.55801944  0.80747857 -0.19129207]
 [ 0.5795626  -0.54421384 -0.60657933]
 [ 0.5939036  -0.22761733  0.77166629]]


In [8]:
print('\nEigenvalues \n%s' %eig_vals)


Eigenvalues 
[2.83259745 0.31323392 0.12689591]


In [9]:
## we can see above that the 1st value of the array is significantly higher so 
## that will be our only x variable
projected_X = x_std.dot(eig_vecs.T[0])
projected_X

array([ 2.12696543, -0.52281694, -1.64859749, -3.27901506,  0.43620122,
        1.63470622,  2.14356202, -1.15139068,  0.55381278, -1.56541207,
        1.15664023,  0.11534434])