In [1]:
import math
import numpy as  np
import  pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

np.random.seed(1)

In [2]:
y_hat = tf.constant(36)
y = tf.constant(39)

loss= (y-y_hat)**2
tf.print(loss)

# Te output is 9 and it makes sense cause (39-36)^2 = (3)^2 = 9

9


In [3]:
x = tf.constant(4, shape=(1,1), dtype = tf.float32)
print(x)

x = tf.constant([[1,2,3],[4,5,6]])
print(x)

x = tf.ones((3,3))
print(x)

x = tf.zeros((3))
tf.print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
[0 0 0]


In [4]:
# so first line converts num 4 to a (1,1) shape array containing  4 as a float value
# so the second command converts the 2D array to a numpy array also gets its shape and data type in it
# so the third one makes a numpy array of ones with the given shape
# so the fourth one makes a numpy array of zeros with the given shape

In [5]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = x + y
tf.print(z)

z = x-y 
tf.print(z)

z = x/y 
tf.print(z)

z = x*y 
tf.print(z)

z = tf.tensordot(x,y, axes=1) 
tf.print(z)

z = x ** 5 
tf.print(z)

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x,y)
tf.print(z)

[10 10 10]
[-8 -6 -4]
[0.1111111111111111 0.25 0.42857142857142855]
[9 16 21]
46
[1 32 243]
[[1.38480699 -1.0687803 0.659322619 0.113862991]
 [-6.27423573 1.23426855 -2.55500078 1.12520552]]


In [6]:
# explain Above

In [7]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)
print(x_ind)

x = tf.constant([[1,2],[3,4],[5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
# explain above

In [9]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [10]:
# explain above

In [11]:
def linear_function():
    np.random.seed(1)
    X = tf.random.uniform((4,3), dtype = tf.float32)
    W = tf.random.normal((3,1), dtype = tf.float32)
    b = tf.random.normal((4,1), dtype = tf.float32)
    Y = tf.add(tf.matmul(X,W),b)
    
    return Y

linear_function()

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.02302885],
       [ 2.5394084 ],
       [ 1.8061678 ],
       [-1.4163511 ]], dtype=float32)>

In [12]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [13]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()
print(x_train.shape)

(60000, 28, 28)


In [14]:
x_train = x_train.reshape(-1,28*28).astype("float32")/255.0
x_test = x_test.reshape(-1,28*28).astype("float32")/255.0

In [15]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
)

In [16]:
model.layers

In [17]:
model = keras.Sequential(
    [
        layers.Dense(200, activation="relu"),
        layers.Dense(100, activation="relu"),
        layers.Dense(10),
    ]
)


model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = keras.optimizers.Adam(lr= 0.00001),
    metrics=['accuracy'],
)

model.fit(x_train,y_train,batch_size=32,epochs=1,verbose=2)

model.evaluate(x_test,y_test, batch_size=32, verbose=2)

C:\Users\Mamoon College\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


1875/1875 - 4s - loss: 1.5668 - accuracy: 0.5964 - 4s/epoch - 2ms/step
313/313 - 1s - loss: 0.9116 - accuracy: 0.8141 - 570ms/epoch - 2ms/step


[0.9116417765617371, 0.8141000270843506]

In [18]:
# Why is the last fully connected layer of size 10? 

# Is cross entropy a good loss function for our problem? 

# How can you get the model to perform greater than 95% accuracy on our images? 
# Rewrite the model in a new cell

In [19]:
inputs = keras.Input(shape=(28*28))
x = layers.Dense(512, activation="relu")(inputs)
x = layers.Dense(256, activation="relu")(x)
outputs = layers.Dense(10, activation="softmax")(x)
model = keras.Model(inputs=inputs,outputs=outputs)


model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer = keras.optimizers.Adam(lr= 0.001),
    metrics=['accuracy'],
)

model.fit(x_train,y_train,batch_size=32,epochs=5,verbose=2)
model.evaluate(x_test,y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 8s - loss: 0.1853 - accuracy: 0.9442 - 8s/epoch - 4ms/step
Epoch 2/5
1875/1875 - 7s - loss: 0.0795 - accuracy: 0.9757 - 7s/epoch - 4ms/step
Epoch 3/5
1875/1875 - 7s - loss: 0.0553 - accuracy: 0.9823 - 7s/epoch - 4ms/step
Epoch 4/5
1875/1875 - 7s - loss: 0.0417 - accuracy: 0.9869 - 7s/epoch - 4ms/step
Epoch 5/5
1875/1875 - 7s - loss: 0.0336 - accuracy: 0.9888 - 7s/epoch - 4ms/step
313/313 - 1s - loss: 0.0814 - accuracy: 0.9763 - 782ms/epoch - 2ms/step


[0.08143273741006851, 0.9763000011444092]

In [20]:
# How is functional different from sequential, and why is it considered more flexible? 
# You may be able to tell by just looking at the code. 

# What accuracy did you obtain, and how can it be improved if at all?


In [21]:
abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])

abalone_train.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.435     0.335   0.110         0.334          0.1355          0.0775   
1   0.585     0.450   0.125         0.874          0.3545          0.2075   
2   0.655     0.510   0.160         1.092          0.3960          0.2825   
3   0.545     0.425   0.125         0.768          0.2940          0.1495   
4   0.545     0.420   0.130         0.879          0.3740          0.1695   

   Shell weight  Age  
0        0.0965    7  
1        0.2250    6  
2        0.3700   14  
3        0.2600   16  
4        0.2300   13

In [22]:
# explain above

In [23]:
abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop('Age')

In [24]:
abalone_features = np.array(abalone_features)
abalone_features

array([[0.435 , 0.335 , 0.11  , ..., 0.1355, 0.0775, 0.0965],
       [0.585 , 0.45  , 0.125 , ..., 0.3545, 0.2075, 0.225 ],
       [0.655 , 0.51  , 0.16  , ..., 0.396 , 0.2825, 0.37  ],
       ...,
       [0.53  , 0.42  , 0.13  , ..., 0.3745, 0.167 , 0.249 ],
       [0.395 , 0.315 , 0.105 , ..., 0.1185, 0.091 , 0.1195],
       [0.45  , 0.355 , 0.12  , ..., 0.1145, 0.0665, 0.16  ]])

In [25]:
abalone_model = tf.keras.Sequential([
  layers.Dense(64),
  layers.Dense(1)
])

abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                      optimizer = tf.keras.optimizers.Adam())

In [26]:
abalone_model.fit(abalone_features, abalone_labels, epochs=10)

Epoch 1/10
104/104 [==============================] - 0s 1ms/step - loss: 62.6570
Epoch 2/10
104/104 [==============================] - 0s 1ms/step - loss: 11.6470
Epoch 3/10
104/104 [==============================] - 0s 1ms/step - loss: 8.4117
Epoch 4/10
104/104 [==============================] - 0s 1ms/step - loss: 7.9308
Epoch 5/10
104/104 [==============================] - 0s 1ms/step - loss: 7.5114
Epoch 6/10
104/104 [==============================] - 0s 1ms/step - loss: 7.1772
Epoch 7/10
104/104 [==============================] - 0s 1ms/step - loss: 6.9245
Epoch 8/10
104/104 [==============================] - 0s 1ms/step - loss: 6.7457
Epoch 9/10
104/104 [==============================] - 0s 1ms/step - loss: 6.6120
Epoch 10/10
104/104 [==============================] - 0s 1ms/step - loss: 6.5094


In [27]:
normalize = layers.Normalization()

In [28]:
normalize.adapt(abalone_features)

In [29]:
norm_abalone_model = tf.keras.Sequential([
  normalize,
  layers.Dense(64),
  layers.Dense(1)
])

norm_abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                           optimizer = tf.keras.optimizers.Adam())

norm_abalone_model.fit(abalone_features, abalone_labels, epochs=10)

Epoch 1/10
104/104 [==============================] - 0s 1ms/step - loss: 93.9253
Epoch 2/10
104/104 [==============================] - 0s 1ms/step - loss: 54.8528
Epoch 3/10
104/104 [==============================] - 0s 1ms/step - loss: 16.6356
Epoch 4/10
104/104 [==============================] - 0s 1ms/step - loss: 5.8241
Epoch 5/10
104/104 [==============================] - 0s 1ms/step - loss: 5.0786
Epoch 6/10
104/104 [==============================] - 0s 2ms/step - loss: 5.0191
Epoch 7/10
104/104 [==============================] - 0s 2ms/step - loss: 4.9868
Epoch 8/10
104/104 [==============================] - 0s 1ms/step - loss: 4.9758
Epoch 9/10
104/104 [==============================] - 0s 1ms/step - loss: 4.9438
Epoch 10/10
104/104 [==============================] - 0s 1ms/step - loss: 4.9281


In [30]:
titanic = pd.read_csv("https://storage.googleapis.com/tf-datasets/titanic/train.csv")
titanic.head()
titanic_features = titanic.copy()
titanic_labels = titanic_features.pop('survived')

In [31]:
# Create a symbolic input
input = tf.keras.Input(shape=(), dtype=tf.float32)

# Perform a calculation using the input
result = 2*input + 1

# the result doesn't have a value
result

<KerasTensor: shape=(None,) dtype=float32 (created by layer 'tf.__operators__.add')>

In [32]:
calc = tf.keras.Model(inputs=input, outputs=result)
print(calc(1).numpy())
print(calc(2).numpy())

3.0
5.0


In [33]:
inputs = {}

for name, column in titanic_features.items():
    dtype = column.dtype
    if dtype == object:
        dtype = tf.string
    else:
        dtype = tf.float32
    
    inputs[name] = tf.keras.Input(shape=(1,), name=name, dtype=dtype)

inputs

{'sex': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'sex')>,
 'age': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'age')>,
 'n_siblings_spouses': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'n_siblings_spouses')>,
 'parch': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'parch')>,
 'fare': <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'fare')>,
 'class': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'class')>,
 'deck': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'deck')>,
 'embark_town': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'embark_town')>,
 'alone': <KerasTensor: shape=(None, 1) dtype=string (created by layer 'alone')>}

In [34]:
numeric_inputs = {name:input for name,input in inputs.items()
                  if input.dtype==tf.float32}

x = layers.Concatenate()(list(numeric_inputs.values()))
norm = layers.Normalization()
norm.adapt(np.array(titanic[numeric_inputs.keys()]))
all_numeric_inputs = norm(x)

all_numeric_inputs

<KerasTensor: shape=(None, 4) dtype=float32 (created by layer 'normalization_1')>

In [35]:
preprocessed_inputs = [all_numeric_inputs]

In [36]:
for name, input in inputs.items():
    if input.dtype == tf.float32:
        continue
    lookup = layers.StringLookup(vocabulary=np.unique(titanic_features[name]))
    one_hot = layers.CategoryEncoding(num_tokens=lookup.vocabulary_size())
    x = lookup(input)
    x = one_hot(x)
    preprocessed_inputs.append(x)

In [37]:
preprocessed_inputs_cat = layers.Concatenate()(preprocessed_inputs)

titanic_preprocessing = tf.keras.Model(inputs, preprocessed_inputs_cat)

tf.keras.utils.plot_model(model = titanic_preprocessing , rankdir="LR", dpi=72, show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [38]:
titanic_features_dict = {name: np.array(value) 
                         for name, value in titanic_features.items()}

In [39]:
features_dict = {name:values[:1] for name, values in titanic_features_dict.items()}
titanic_preprocessing(features_dict)

<tf.Tensor: shape=(1, 28), dtype=float32, numpy=
array([[-0.610415  ,  0.395198  , -0.4790527 , -0.49740276,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ,  0.        ]], dtype=float32)>

In [40]:
def titanic_model(preprocessing_head, inputs):
    body = tf.keras.Sequential([
        layers.Dense(64),
        layers.Dense(1)
      ])
    preprocessed_inputs = preprocessing_head(inputs)
    result = body(preprocessed_inputs)
    model = tf.keras.Model(inputs, result)

    model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                optimizer=tf.keras.optimizers.Adam())
    return model

titanic_model = titanic_model(titanic_preprocessing, inputs)

In [41]:
titanic_model.fit(x=titanic_features_dict, y=titanic_labels, epochs=10)

Epoch 1/10
20/20 [==============================] - 1s 2ms/step - loss: 0.6979
Epoch 2/10
20/20 [==============================] - 0s 2ms/step - loss: 0.5535
Epoch 3/10
20/20 [==============================] - 0s 2ms/step - loss: 0.4929
Epoch 4/10
20/20 [==============================] - 0s 2ms/step - loss: 0.4621
Epoch 5/10
20/20 [==============================] - 0s 2ms/step - loss: 0.4486
Epoch 6/10
20/20 [==============================] - 0s 2ms/step - loss: 0.4390
Epoch 7/10
20/20 [==============================] - 0s 2ms/step - loss: 0.4300
Epoch 8/10
20/20 [==============================] - 0s 2ms/step - loss: 0.4279
Epoch 9/10
20/20 [==============================] - 0s 2ms/step - loss: 0.4243
Epoch 10/10
20/20 [==============================] - 0s 2ms/step - loss: 0.4239


In [42]:
titanic_model.save('test')
reloaded = tf.keras.models.load_model('test')

INFO:tensorflow:Assets written to: test\assets


In [43]:
features_dict = {name:values[:1] for name, values in titanic_features_dict.items()}

before = titanic_model(features_dict)
after = reloaded(features_dict)
assert (before-after)<1e-3
print(before)
print(after)

tf.Tensor([[-1.8036731]], shape=(1, 1), dtype=float32)
tf.Tensor([[-1.8036731]], shape=(1, 1), dtype=float32)


In [44]:
import itertools

def slices(features):
    for i in itertools.count():
        # For each feature take index `i`
        example = {name:values[i] for name, values in features.items()}
        yield example

In [45]:
for example in slices(titanic_features_dict):
    for name, value in example.items():
        print(f"{name:19s}: {value}")
    break

sex                : male
age                : 22.0
n_siblings_spouses : 1
parch              : 0
fare               : 7.25
class              : Third
deck               : unknown
embark_town        : Southampton
alone              : n


In [46]:
features_ds = tf.data.Dataset.from_tensor_slices(titanic_features_dict)

In [47]:
for example in features_ds:
    for name, value in example.items():
        print(f"{name:19s}: {value}")
    break

sex                : b'male'
age                : 22.0
n_siblings_spouses : 1
parch              : 0
fare               : 7.25
class              : b'Third'
deck               : b'unknown'
embark_town        : b'Southampton'
alone              : b'n'


In [48]:
titanic_ds = tf.data.Dataset.from_tensor_slices((titanic_features_dict, titanic_labels))

In [49]:
titanic_batches = titanic_ds.shuffle(len(titanic_labels)).batch(32)

In [50]:
titanic_model.fit(titanic_batches, epochs=5)

Epoch 1/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4224
Epoch 2/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4217
Epoch 3/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4224
Epoch 4/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4222
Epoch 5/5
20/20 [==============================] - 0s 2ms/step - loss: 0.4201


In [51]:
titanic_file_path = tf.keras.utils.get_file("train.csv", "https://storage.googleapis.com/tf-datasets/titanic/train.csv")

In [52]:
titanic_csv_ds = tf.data.experimental.make_csv_dataset(
    titanic_file_path,
    batch_size=5, # Artificially small to make examples easier to show.
    label_name='survived',
    num_epochs=1,
    ignore_errors=True,)

In [53]:
for batch, label in titanic_csv_ds.take(1):
    for key, value in batch.items():
        print(f"{key:20s}: {value}")
    print()
    print(f"{'label':20s}: {label}")

sex                 : [b'male' b'female' b'male' b'male' b'male']
age                 : [50. 50. 28. 50. 36.]
n_siblings_spouses  : [1 0 0 2 1]
parch               : [0 1 0 0 0]
fare                : [106.425  26.      8.05  133.65   15.55 ]
class               : [b'First' b'Second' b'Third' b'First' b'Third']
deck                : [b'C' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town         : [b'Cherbourg' b'Southampton' b'Southampton' b'Southampton' b'Southampton']
alone               : [b'n' b'n' b'y' b'n' b'n']

label               : [0 1 0 1 0]
