In [1]:
import numpy as np

In [2]:
Python_list = [1,2,3,4,5]
print(Python_list)
print(type(Python_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
numpy_array = np.array(Python_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
python_2DArray = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]] 
print(python_2DArray)
print(type(python_2DArray))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


In [5]:
numpy_2DArray = np.array(python_2DArray)
print(numpy_2DArray)
print(type(numpy_2DArray))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [6]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [8]:
np.arange(15,0)

array([], dtype=int32)

In [9]:
np.arange(15,0,-1)

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [10]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
np.arange(0,16).reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [13]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(15).reshape(3,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros(15).reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones(15).reshape(3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones(15).reshape(15,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [19]:
np.ones(15).reshape(1,15)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.ones(15, dtype=int).reshape(3,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.zeros(15, dtype=int).reshape(5,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.eye(1)

array([[1.]])

In [24]:
np.random.rand(5)

array([0.50971158, 0.66395953, 0.05256816, 0.13394126, 0.97908886])

In [25]:
np.random.randn(5)

array([ 0.2555998 ,  1.28641492, -0.66673189,  3.41644014,  0.29559299])

In [26]:
np.random.randn()

-0.6555814721219821

In [27]:
np.random.randint(1,100)

58

In [28]:
np.random.randint(-100,100)

-9

In [29]:
np.random.randint(1, 100, 15)

array([57, 35, 60,  6, 70, 82, 91, 62, 98, 42, 87, 43, 67,  2, 77])

In [30]:
A = np.random.randint(0, 100, 20).reshape(4, 5)
A

array([[38, 30, 23, 43, 45],
       [23, 94, 31, 35, 26],
       [83,  1, 13, 11, 17],
       [29,  2, 79, 17, 68]])

In [31]:
B = np.random.randn(6).reshape(3,2)
B

array([[-1.36496744, -0.18074238],
       [-0.06038058, -0.689884  ],
       [ 1.25379958,  0.29387167]])

In [32]:
print(f'The smallest value in A is {A.min()}, and is a located at position {A.argmin() } ' )
print(f'The largest value in A is {A.max()}, and is a located at position {A.argmax()} ')

The smallest value in A is 1, and is a located at position 11 
The largest value in A is 94, and is a located at position 6 


In [33]:
A.shape

(4, 5)

In [34]:
A.reshape(5,4)

array([[38, 30, 23, 43],
       [45, 23, 94, 31],
       [35, 26, 83,  1],
       [13, 11, 17, 29],
       [ 2, 79, 17, 68]])

In [35]:
np.shape(A)

(4, 5)

In [36]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0, 4).reshape(2, 2)
D = np.arange(0, 4).reshape(2, 2)
E = np.arange(1, 16).reshape(3, 5)
F = np.arange(11)
print(f'A: {A}')
print(f'B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


In [37]:
A + B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [38]:
A + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
A - B

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14])

In [40]:
A - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
A * B

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231, 276, 325,
       378, 435])

In [42]:
A * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [43]:
A / B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138])

In [44]:
A / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5])

In [45]:
A % B

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int32)

In [46]:
A % 2 

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [47]:
C

array([[0, 1],
       [2, 3]])

In [48]:
D

array([[0, 1],
       [2, 3]])

In [49]:
np.matmul(C,D)

array([[ 2,  3],
       [ 6, 11]])

In [50]:
np.sqrt(E)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [51]:
np.log(E)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [52]:
np.where(F%2==0, 1,
F*100)

array([  1, 100,   1, 300,   1, 500,   1, 700,   1, 900,   1])

In [53]:
np.where(F%2 == 0 , "even", "odd")

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even'], dtype='<U4')

In [54]:
A  = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
print(f'A[0] : {A[0]}')
print(f'A[5] : {A[5]}')
print(f'A[14] : {A[14]}')

A[0] : 0
A[5] : 5
A[14] : 14


In [56]:
print("A[0] : " )
print(A[0])
print("A[5] : " )
print(A[5])
print("A[14] : " )
print(A[14])

A[0] : 
0
A[5] : 
5
A[14] : 
14


In [57]:
A[0 :10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
print(f' Loading the first 10 element {A[0:10]}')

 Loading the first 10 element [0 1 2 3 4 5 6 7 8 9]


In [59]:
print(f' changing the first 10 element {A[0:10]} to 500')
A[0:10] = 500
print(f' Loading the new first 10 element {A[0:10]}')

 changing the first 10 element [0 1 2 3 4 5 6 7 8 9] to 500
 Loading the new first 10 element [500 500 500 500 500 500 500 500 500 500]


In [60]:
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,  11,  12,
        13,  14])

In [61]:
B = np.arange(50).reshape(5,10)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
print(f'0th row and 2nd col in B: {B[0, 2]}')
print(f'3rd row and 3rd col in B: {B[3, 3]}')
print(f'4th row and 2nd col in B: {B[4, 2]}')

0th row and 2nd col in B: 2
3rd row and 3rd col in B: 33
4th row and 2nd col in B: 42


In [63]:
B[0:2, 3:5]

array([[ 3,  4],
       [13, 14]])

In [64]:
B[0:2, 3:5] = 1
B

array([[ 0,  1,  2,  1,  1,  5,  6,  7,  8,  9],
       [10, 11, 12,  1,  1, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [65]:
C = np.arange(50).reshape(10, 5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [66]:
C%2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [67]:
(C%2 == 0).sum()

25

In [68]:
C[C%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])